service:
  environment: ${ENVIRONMENT:development}

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: INFO
    Exposed: DEBUG
    dev.nixgeek.bliki:
      lib: DEBUG
      service: DEBUG
    org.jetbrains.exposed: DEBUG
    org.springframework:
      boot:
        autoconfigure: INFO
        actuate: INFO
      web: DEBUG
    zaxxer.hikari:
      pool:
        HikariPool: DEBUG
      HikariConfig: DEBUG

security:
  jwt:
    secret: ${JWT_SECRET:dev_0nly!Ch4ngeME}

database:
  app:
    host: ${DB_HOST_APP:localhost}
    port: ${DB_PORT_APP:5432}
    password: ${DB_PASS_APP:dev_ChangeM3}
  admin:
    host: ${DB_HOST_ADMIN:localhost}
    port: ${DB_PORT_ADMIN:5432}
    password: ${DB_PASS_ADMIN:dev_ChangeM3}
