service:
  name: service-bliki

server:
  port: '8080'
  max-http-request-header-size: '64000'
  shutdown: graceful
  http2:
    enabled: true
  netty:
    connection-timeout: 30s
    idle-timeout: 60s

management:
  endpoints:
    web:
      base-path: /service/manage
      discovery:
        enabled: true
      exposure:
        include: "health,info,env,mappings,loggers"
    jmx:
      domain: bliki.nixgeek.dev
      exposure:
        include: "health,info,env,mappings,loggers"
  endpoint:
    health:
      access: unrestricted
      show-components: always
      show-details: always
      probes:
        enabled: true
    info:
      access: unrestricted
    env:
      access: unrestricted
      keys-to-sanitize: "password, secret, key, token, .*credentials.*"
    mappings:
      access: unrestricted
    loggers:
      access: unrestricted
  health:
    ping:
      enabled: true
    db:
      enabled: true
    diskspace:
      enabled: true
  info:
    os:
      enabled: true
    java:
      enabled: true
    env:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true
      mode: full

spring:
  application:
    name: service-bliki
  main:
    web-application-type: reactive
  webflux:
    base-path: /
    format:
      date: yyyy-MM-dd HH:mm:ss
  jmx:
    unique-names: true
  lifecycle:
    timeout-per-shutdown-phase: 15s
  web:
    error:
      include-message: always
      include-stacktrace: always

security:
  jwt:
    issuer: bliki-service
    access-token-ttl-seconds: 3600

database:
  app:
    name: ${DB_NAME_APP:bliki}
    username: ${DB_USER_APP}
    schema: ${DB_SCHEMA_APP:bliki}
    connection_pool_size: ${DB_CONNECTION_POOL_SIZE_APP}
    isolation_level: ${DB_ISOLATION_LEVEL:TRANSACTION_READ_COMMITTED}
    max_lifetime: ${DB_MAX_LIFETIME:1800000}
    db_type: ${DB_TYPE:postgresql}
    default_database: ${DB_DEFAULT_DATABASE_APP}
    auto_commit: ${DB_AUTO_COMMIT:true}
    leak_detection_threshold_ms: ${DB_LEAK_DETECTION_THRESHOLD:120000}
  admin:
    name: ${DB_NAME_ADMIN:bliki}
    username: ${DB_USER_ADMIN}
    schema: ${DB_SCHEMA_ADMIN:bliki}
    connection_pool_size: ${DB_CONNECTION_POOL_SIZE_ADMIN}
    isolation_level: ${DB_ISOLATION_LEVEL:TRANSACTION_READ_COMMITTED}
    max_lifetime: ${DB_MAX_LIFETIME:1800000}
    db_type: ${DB_TYPE:postgresql}
    default_database: ${DB_DEFAULT_DATABASE_ADMIN}
    auto_commit: ${DB_AUTO_COMMIT:true}
    leak_detection_threshold_ms: ${DB_LEAK_DETECTION_THRESHOLD:120000}
