# avoid OOMs due to ClassGraph - https://kotest.io/docs/framework/project-config.html#runtime-detection
kotest.framework.parallelism=8
kotest.framework.discovery.jar.scan.disable=true
kotest.framework.classpath.scanning.config.disable=true
kotest.framework.classpath.scanning.autoscan.disable=true
kotest.framework.config.fqn=dev.nixgeek.bliki.lib.test.fixtures.TestProjectConfig
