### Login - Username + Password
POST http://localhost:8080/service/login
Accept: application/json
Content-Type: application/json

{
    "email": "jgorauskas@gmail.com",
    "password": "secret!123"
}

###

