[versions]
java-language = "21"
kotlin-language = "2.3.0"

exposed-version = "1.0.0"
jackson-version = "3.0.4"
kotest-version = "6.1.3"
kotlinx-coroutines = "1.10.2"
mockk-version = "1.14.9"
springboot-version = "4.0.2"
test-containers-version = "2.0.3"

[libraries]
kotlin-stdlib-core = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin-language" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin-language" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor", version.ref = "kotlinx-coroutines" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin-language" }

jakarta-validation-api = { module = "jakarta.validation:jakarta.validation-api", version = "3.1.1" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version = "7.0.14" }
logback-classic = { module = "ch.qos.logback:logback-classic", version = "1.5.28" }
netty-macos-dns-resolver = { module = "io.netty:netty-resolver-dns-native-macos", version = "4.2.10.Final" }
reactor-kotlin-extensions = { module = "io.projectreactor.kotlin:reactor-kotlin-extensions", version = "1.3.0" }
squareup-okhttp = { module = "com.squareup.okhttp3:okhttp", version = "5.3.2" }

exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed-version" }
exposed-crypt = { module = "org.jetbrains.exposed:exposed-crypt", version.ref = "exposed-version" }
exposed-json = { module = "org.jetbrains.exposed:exposed-json", version.ref = "exposed-version" }
exposed-r2dbc = { module = "org.jetbrains.exposed:exposed-r2dbc", version.ref = "exposed-version" }
exposed-time = { module = "org.jetbrains.exposed:exposed-kotlin-datetime", version.ref = "exposed-version" }
exposed-migration-core = { module = "org.jetbrains.exposed:exposed-migration-core", version.ref = "exposed-version" }
exposed-migration-r2dbc = { module = "org.jetbrains.exposed:exposed-migration-r2dbc", version.ref = "exposed-version" }
postgresql-r2dbc = { module = "org.postgresql:r2dbc-postgresql", version = "1.1.1.RELEASE" }
r2dbc-spi = { module = "io.r2dbc:r2dbc-spi", version = "1.0.0.RELEASE" }
r2dbc-pool = { module = "io.r2dbc:r2dbc-pool", version = "1.0.2.RELEASE" }

jackson-core = { module = "tools.jackson.core:jackson-core", version.ref = "jackson-version" }
jackson-databind = { module = "tools.jackson.core:jackson-databind", version.ref = "jackson-version" }
jackson-module-kotlin = { module = "tools.jackson.module:jackson-module-kotlin", version.ref = "jackson-version" }

spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor", version.ref = "springboot-version" }
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools", version.ref = "springboot-version" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator", version.ref = "springboot-version" }
spring-boot-starter-r2dbc = { module = "org.springframework.boot:spring-boot-starter-r2dbc", version.ref = "springboot-version" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security", version.ref = "springboot-version" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation", version.ref = "springboot-version" }
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux", version.ref = "springboot-version" }

kotest-assertions = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest-version" }
kotest-core = { module = "io.kotest:kotest-framework-engine-jvm", version.ref = "kotest-version" }
kotest-extension-spring = { module = "io.kotest:kotest-extensions-spring", version.ref = "kotest-version" }
kotest-extension-testcontainers = { module = "io.kotest:kotest-extensions-testcontainers", version.ref = "kotest-version" }
kotest-property = { module = "io.kotest:kotest-property-jvm", version.ref = "kotest-version" }
kotest-runner = { module = "io.kotest:kotest-runner-junit6-jvm", version.ref = "kotest-version" }
test-containers-postgresql = { module = "org.testcontainers:testcontainers-postgresql", version.ref = "test-containers-version" }
test-containers-r2dbc = { module = "org.testcontainers:testcontainers-r2dbc", version.ref = "test-containers-version" }
test-kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
test-mockk = { module = "io.mockk:mockk-jvm", version.ref = "mockk-version" }
test-mockk-dsl = { module = "io.mockk:mockk-dsl-jvm", version.ref = "mockk-version" }
test-reactor = { module = "io.projectreactor:reactor-test", version = "3.7.11" }
test-spring-boot-containers = { module = "org.springframework.boot:spring-boot-testcontainers", version.ref = "springboot-version" }
test-spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "springboot-version" }
test-spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator-test", version.ref = "springboot-version" }
test-spring-boot-starter-r2dbc = { module = "org.springframework.boot:spring-boot-starter-r2dbc-test", version.ref = "springboot-version" }
test-spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security-test", version.ref = "springboot-version" }
test-spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux-test", version.ref = "springboot-version" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-language" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin-language" }
google-osdetector = { id = "com.google.osdetector", version = "1.7.3" }
kotest = { id = "io.kotest", version.ref = "kotest-version" }
spring-boot-gradle = { id = "org.springframework.boot", version.ref = "springboot-version" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.7" }
