[versions]
java-language = "21"
kotlin-language = "2.3.0"

exposed-version = "1.1.1"
flyway-version = "12.0.3"
jackson-version = "3.0.4"
kotest-version = "6.1.3"
kotlinx-coroutines = "1.10.2"
mockk-version = "1.14.9"
springboot-version = "4.0.2"
test-containers-version = "2.0.3"

[libraries]
kotlin-stdlib-core = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin-language" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin-language" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor", version.ref = "kotlinx-coroutines" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version = "7.0.14" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin-language" }
kotlin-ulid = { module = "com.aallam.ulid:ulid-kotlin-jvm", version = "1.6.0" }

jakarta-validation-api = { module = "jakarta.validation:jakarta.validation-api", version = "3.1.1" }
java-diff-utils = { module = "io.github.java-diff-utils:java-diff-utils", version = "4.16" }
logback-classic = { module = "ch.qos.logback:logback-classic", version = "1.5.28" }
netty-macos-dns-resolver = { module = "io.netty:netty-resolver-dns-native-macos", version = "4.2.10.Final" }
reactor-kotlin-extensions = { module = "io.projectreactor.kotlin:reactor-kotlin-extensions", version = "1.3.0" }
squareup-okhttp = { module = "com.squareup.okhttp3:okhttp", version = "5.3.2" }

exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed-version" }
exposed-crypt = { module = "org.jetbrains.exposed:exposed-crypt", version.ref = "exposed-version" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed-version" }
exposed-json = { module = "org.jetbrains.exposed:exposed-json", version.ref = "exposed-version" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed-version" }
exposed-time = { module = "org.jetbrains.exposed:exposed-kotlin-datetime", version.ref = "exposed-version" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway-version" }
flyway-database-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway-version" }
hikari-cp = { module = "com.zaxxer:HikariCP", version = "7.0.2" }
postgresql-driver = { module = "org.postgresql:postgresql", version = "42.7.10" }

jackson-core = { module = "tools.jackson.core:jackson-core", version.ref = "jackson-version" }
jackson-databind = { module = "tools.jackson.core:jackson-databind", version.ref = "jackson-version" }
jackson-module-kotlin = { module = "tools.jackson.module:jackson-module-kotlin", version.ref = "jackson-version" }
redisson = { module = "org.redisson:redisson", version = "4.3.0" }

spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor", version.ref = "springboot-version" }
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools", version.ref = "springboot-version" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator", version.ref = "springboot-version" }
spring-boot-starter-jdbc = { module = "org.springframework.boot:spring-boot-starter-jdbc", version.ref = "springboot-version" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security", version.ref = "springboot-version" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation", version.ref = "springboot-version" }
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux", version.ref = "springboot-version" }

kotest-assertions = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest-version" }
kotest-core = { module = "io.kotest:kotest-framework-engine-jvm", version.ref = "kotest-version" }
kotest-extension-spring = { module = "io.kotest:kotest-extensions-spring", version.ref = "kotest-version" }
kotest-extension-testcontainers = { module = "io.kotest:kotest-extensions-testcontainers", version.ref = "kotest-version" }
kotest-property = { module = "io.kotest:kotest-property-jvm", version.ref = "kotest-version" }
kotest-runner = { module = "io.kotest:kotest-runner-junit6-jvm", version.ref = "kotest-version" }
test-containers-postgresql = { module = "org.testcontainers:testcontainers-postgresql", version.ref = "test-containers-version" }
test-kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
test-mockk = { module = "io.mockk:mockk-jvm", version.ref = "mockk-version" }
test-mockk-dsl = { module = "io.mockk:mockk-dsl-jvm", version.ref = "mockk-version" }
test-reactor = { module = "io.projectreactor:reactor-test", version = "3.7.11" }
test-spring-boot-testcontainers = { module = "org.springframework.boot:spring-boot-testcontainers", version.ref = "springboot-version" }
test-spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "springboot-version" }
test-spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator-test", version.ref = "springboot-version" }
test-spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security-test", version.ref = "springboot-version" }
test-spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux-test", version.ref = "springboot-version" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-language" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin-language" }
flyway-gradle = { id = "org.flywaydb.flyway", version.ref = "flyway-version" }
google-osdetector = { id = "com.google.osdetector", version = "1.7.3" }
kotest = { id = "io.kotest", version.ref = "kotest-version" }
spring-boot-gradle = { id = "org.springframework.boot", version.ref = "springboot-version" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.7" }

[bundles]
kotlin = ["kotlin-stdlib-core", "kotlin-stdlib-jdk8", "kotlin-reflect"]
coroutines = ["kotlinx-coroutines-core", "kotlinx-coroutines-jdk8", "kotlinx-coroutines-reactor"]
database = [
    "exposed-core", "exposed-jdbc", "exposed-crypt", "exposed-time", "exposed-json", "exposed-dao",
    "hikari-cp", "postgresql-driver",
]
jackson = ["jackson-core", "jackson-databind", "jackson-module-kotlin", "redisson"]
logging = ["logback-classic", "kotlin-logging"]
spring-boot-starters = [
    "spring-boot-starter-actuator", "spring-boot-starter-security", "spring-boot-starter-jdbc",
    "spring-boot-starter-validation", "spring-boot-starter-webflux",
]
kotest = [
    "kotest-assertions", "kotest-core", "kotest-extension-spring", "kotest-extension-testcontainers",
    "kotest-property", "kotest-runner",
]
test = ["test-containers-postgresql", "test-kotlinx-coroutines", "test-mockk", "test-mockk-dsl", "test-reactor"]
test-spring-boot = [
    "test-spring-boot-testcontainers", "test-spring-boot-starter", "test-spring-boot-starter-actuator",
    "test-spring-boot-starter-security", "test-spring-boot-starter-webflux",
]
